### ISSUE TITLE
How to set volumes/persistent data for docker

### ISSUE THREAD

**Issue by SourCandy80** [rezonmain/mc-server-scanner#2]
Title says all. I am new to docker and was wondering how it would be done. I want to be able to stop and start the scanner at anytime

**Comment by SourCandy80** [comment]
Nevermind. Im stupid. Its running in docker of course. I keep getting an error with this:

```
mc-server-scanner-worker-1   | [2023-06-16 08:12:27,589] [PID 8] [Thread-4] [dramatiq.worker.WorkerThread] [ERROR] Failed to process message write_to_db() with unhandled exception.
mc-server-scanner-worker-1   | Traceback (most recent call last):
mc-server-scanner-worker-1   |   File "/src/dramatiq_actors.py", line 66, in write_to_db
mc-server-scanner-worker-1   |     res = db.insert_many(entries)
mc-server-scanner-worker-1   |           ^^^^^^^^^^^^^^^^^^^^^^^
mc-server-scanner-worker-1   |   File "/src/mongo.py", line 23, in insert_many
mc-server-scanner-worker-1   |     res = self.coll.insert_many(serverArr)
mc-server-scanner-worker-1   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mc-server-scanner-worker-1   |   File "/usr/local/lib/python3.11/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
mc-server-scanner-worker-1   |     return func(self, *args, **kwargs)
mc-server-scanner-worker-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
mc-server-scanner-worker-1   |   File "/usr/local/lib/python3.11/site-packages/pymongo/collection.py", line 707, in insert_many
mc-server-scanner-worker-1   |     blk.execute(write_concern, session=session)
mc-server-scanner-worker-1   |   File "/usr/local/lib/python3.11/site-packages/pymongo/bulk.py", line 513, in execute
mc-server-scanner-worker-1   |     return self.execute_command(generator, write_concern, session)
mc-server-scanner-worker-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mc-server-scanner-worker-1   |   File "/usr/local/lib/python3.11/site-packages/pymongo/bulk.py", line 390, in execute_command
mc-server-scanner-worker-1   |     with client._tmp_session(session) as s:
mc-server-scanner-worker-1   |   File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
mc-server-scanner-worker-1   |     return next(self.gen)
mc-server-scanner-worker-1   |            ^^^^^^^^^^^^^^
mc-server-scanner-worker-1   |   File "/usr/local/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1729, in _tmp_session
mc-server-scanner-worker-1   |     s = self._ensure_session(session)
mc-server-scanner-worker-1   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mc-server-scanner-worker-1   |   File "/usr/local/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1712, in _ensure_session
mc-server-scanner-worker-1   |     return self.__start_session(True, causal_consistency=False)
mc-server-scanner-worker-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mc-server-scanner-worker-1   |   File "/usr/local/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1657, in __start_session
mc-server-scanner-worker-1   |     self._topology._check_implicit_session_support()
mc-server-scanner-worker-1   |   File "/usr/local/lib/python3.11/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
mc-server-scanner-worker-1   |     self._check_session_support()
mc-server-scanner-worker-1   |   File "/usr/local/lib/python3.11/site-packages/pymongo/topology.py", line 554, in _check_session_support
mc-server-scanner-worker-1   |     self._select_servers_loop(
mc-server-scanner-worker-1   |   File "/usr/local/lib/python3.11/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
mc-server-scanner-worker-1   |     raise ServerSelectionTimeoutError(
mc-server-scanner-worker-1   | pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 648c194d74cb50f1d7b4f6e8, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused')>]>
mc-server-scanner-worker-1   | 
mc-server-scanner-worker-1   | During handling of the above exception, another exception occurred:
mc-server-scanner-worker-1   | 
mc-server-scanner-worker-1   | Traceback (most recent call last):
mc-server-scanner-worker-1   |   File "/usr/local/lib/python3.11/site-packages/dramatiq/worker.py", line 485, in process_message
mc-server-scanner-worker-1   |     res = actor(*message.args, **message.kwargs)
mc-server-scanner-worker-1   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mc-server-scanner-worker-1   |   File "/usr/local/lib/python3.11/site-packages/dramatiq/actor.py", line 177, in __call__
mc-server-scanner-worker-1   |     return self.fn(*args, **kwargs)
mc-server-scanner-worker-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^
mc-server-scanner-worker-1   |   File "/src/dramatiq_actors.py", line 76, in write_to_db
mc-server-scanner-worker-1   |     raise Exception(f'An {Color.RED}error{Color.END} ocurred on trying to write entries to mongo database, Error: {e}')
mc-server-scanner-worker-1   | Exception: An error ocurred on trying to write entries to mongo database, Error: 127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 648c194d74cb50f1d7b4f6e8, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused')>]>
mc-server-scanner-worker-1   | [2023-06-16 08:12:27,606] [PID 8] [Thread-4] [dramatiq.middleware.retries.Retries] [WARNING] Retries exceeded for message '4b20efb0-64ff-4e65-8fba-d20f549619c2'.

```

**Comment by SourCandy80** [comment]
Also if possible, any help on setting up the website?

**Comment by SourCandy80** [comment]
Also i like the site. Instructions wouldve been good but I figured it out!
